import type { Metadata } from 'next';
import { Inter, IBM_Plex_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';

const IBMPlexMono = IBM_Plex_Mono({
  style: ['normal', 'italic'],
  weight: ['500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Moirai.js',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={IBMPlexMono.className}>
        <div className="h-full">
          <Navbar />
          {children}
          <footer>
            <p className="flex h-10 items-center justify-center border-t-2 border-green-600 text-center">
              © {new Date().getFullYear()} Moirai.js
            </p>{' '}
          </footer>
        </div>
      </body>
    </html>
  );
}
